# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo 'Hello world'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mkdir 'testFolder'
      ls

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '--output $(Build.ArtifactStagingDirectory)'
    artifact: 'myweb'
    publishLocation: 'pipeline'




